from pyodbc import Cursor

from .ConnThread import ConnThread
from .Table import Table

DATA_TYPES: list
DB_NAME: str
def __get_conn_thread() -> ConnThread:...
def get_cursor() -> Cursor:...
def get_db_name():...
def get_data_types():...
def find_type_by_sqltype(sql_type: int) -> str:...
def db_connect(driver: str, server: str, port: str or int, db: str, user='', password='', autocomm=True) -> None:...
def db_disconnect() -> None:...
def db_read_table(table: str or Table, limit=int, sql_condition=str, order_by=('', '')) -> list:...
def db_execute_query(query: str) -> list or bool:...
def db_create(db_name: str) -> bool:...
def db_change(db_name: str) -> bool:...
def db_drop(db_name: str) -> bool:...
def import_csv_db(table_name:str, path:str, delimiter=',', quotechar=';') -> bool:...
def import_xl_db(table_name:str, path:str) -> bool:...